Areas/Admin/Controllers/InternalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Xml;
using Vogel.Areas.Admin.Data;
using Vogel.Areas.Admin.Models;
using Vogel.Controllers;
using Vogel.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Vogel.Models;

namespace Vogel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class InternalController : BaseController
    {
        public InternalController(MainDbContext mainContext, AdminDbContext adminContext) 
            : base(mainContext, adminContext)
        {
        }

        public IActionResult Index()
        {
            AddCSS(new string[] { "admin1" });
            AddJS(new string[] { "app" });

            ViewBag.Error = false;

            var error = Request.Cookies["Error"];
            if (error != null)
            {
                ViewBag.Error = bool.Parse(error);

                Response.Cookies.Append("Error", "False");
            }

            return View();
        }

        public IActionResult CreateUser(string auth, string name, string pwd)
        {
            if (auth != Secure.MasterData.PWD) return BadRequest();

            User nuser = new User
            {
                Name = name,
                Pwd = cry.Encrypt(Encoding.ASCII.GetBytes(pwd), RSAEncryptionPadding.OaepSHA256)
            };

            _adminContext.User.Add(nuser);

            _adminContext.SaveChanges();

            return Ok("User " + name + " Created!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([FromForm] string username, [FromForm] string password)
        {
            if (DoLogin(username, password)) return RedirectPermanent("/Admin/Internal/Manage");
            else return RedirectPermanent("/Admin");
        }

        [NonAction]
        private IActionResult ErrorReturn()
        {
            Response.Cookies.Append("Error", "True");

            return RedirectPermanent("/Admin");
        }

        // -- Logged in

        public IActionResult Manage()
        {
            if (ValidateLogin())
            {
                AddCSS(new string[] { "admin0" });
                AddJS(new string[] { "admin" });

                ViewBag.Context = _mainContext;

                return View();
            }
            else
            {
                Response.Cookies.Append("Error", "True");

                return RedirectPermanent("/Admin");
            }
        }

        public IActionResult Files([FromQuery] int? oreoId)
        {
            if (!ValidateLogin()) return Unauthorized();

            oreoId ??= -1;

            if (oreoId == -1) return BadRequest();

            var oreo = _mainContext.Oreo.Find(oreoId);

            if (oreo == null) return BadRequest();

            ViewBag.Oreo = oreo;
            ViewBag.Context = _mainContext;

            return View();
        }

        public IActionResult UploadFile([FromBody] string imgBase64)
        {
            if (!ValidateLogin()) return Unauthorized();

            if (imgBase64 == null || imgBase64.Length < 1) return BadRequest();

            Image nimage = new Image {
                Url = Request.Headers["x-Oreo-FileName"],
                Base64 = imgBase64
            };

            _mainContext.Image.Add(nimage);

            _mainContext.SaveChanges();

            return Ok();
        }
    }
}

Areas/Admin/Views/Internal/Files.cshtml
@{
    var oreo = (Oreo)ViewBag.Oreo;
    var context = (MainDbContext)ViewBag.Context;

    var currentImage = context.GetImage(oreo);
}

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/files.css" />
</head>
<body>
    <div class="current-display">
        <span>Current:</span>
        <div class="current-display-save">
            <img data-name="@currentImage.Url" src="@currentImage.GetEffectiveSource()" draggable="false" />
            <div data-selected style="display: none;">
                <a class="a-hover grid-center">Save</a>
                @{
                    await Html.RenderPartialAsync(
                        "Partial/LoadingPartial",
                        new Loading
                        {
                            CSSClasses = "grid-center"
                        });
                }
            </div>
        </div>
    </div>
    <div class="upload-preview">
        <div class="upload">
            <span>Upload</span>
            <div>
                <input id="upload_img" type="file" accept="jpg, jpeg, png" />
            </div>
            <div class="upload-a">
                <div>
                    <a class="a-hover">Submit</a>
                    @{
                        await Html.RenderPartialAsync("Partial/LoadingPartial", new Loading { });
                    }
                </div>
            </div>
        </div>
        <div>
            <img id="upload_preview" style="display: none;" src="" />
        </div>
    </div>
    <div>
        <span>Available</span>
        <div>
            <label for="available_filter">Search</label>
            <input id="available_filter" type="text" autocomplete="off" />
        </div>
        <div class="selection-available">
            @{
                var images = context.Image.ToArray();

                for (int i = 0, l = images.Length; i < l; i++)
                {
                    var nimage = images[i];
                    <div id="image_@nimage.Id" data-name="@nimage.Url" onclick="selectImage(@nimage.Id)" style="display: grid;" class="selection-image">
                        <img src="@nimage.GetEffectiveSource()" draggable="false" />
                        <span>@nimage.Url</span>
                    </div>
                }
            }
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/files.js"></script>
</body>
</html>

Areas/Admin/Views/Internal/Index.cshtml
@{
    Layout = "_Layout";

    ViewData["Title"] = "Administration";
    ViewData["LoggedIn"] = false;
}

<h2>Admin</h2>

@using (Html.BeginForm("Login", "Internal", FormMethod.Post))
{
    if (ViewBag.Error)
    {
        <style>
            .admin-mask {
                --border-in: 1px solid red;
            }
        </style>
    }
    else
    {
        <style>
            .admin-mask {
                --border-in: 1px solid black;
            }
        </style>
    }

    <div class="admin-mask">
        <span>Username:</span>
        <input id="ausr" name="Username" type="text" style="border: var(--border-in);" />

        <span>Password:</span>
        <input id="apwd" name="Password" type="password" style="border: var(--border-in);" />

        <a id="alogin" class="a-hover">Login</a>
    </div>
    @Html.AntiForgeryToken()
    <input id="asubmit" type="submit" style="display: none;" />
}

Areas/Admin/Views/Internal/Manage.cshtml
@{
    Layout = "_Layout";

    ViewData["Title"] = "Administration";

    var _context = (MainDbContext)ViewBag.Context;

    var Oreos = _context.Oreo.ToArray();
}

<h2>Internal Area</h2>

<div id="file_browser" style="display: none;" class="file-selector">
    <div>
        <div class="file-selector-ribbon">
            <span>Files</span>
            <a class="a-hover" onclick="closeFileBrowser(-1)">X</a>
        </div>
        <div class="file-explorer">
            <div style="display: grid;">
                @{
                    await Html.RenderPartialAsync(
                        "Partial/LoadingPartial", 
                        new Loading 
                        {
                            DefaultActive = true,
                            CSSClasses = "grid-center"
                        });
                }
            </div>
            <iframe src="" style="display: none;"></iframe>
        </div>
    </div>
</div>

<div class="card-columns oreo-columns">
    @foreach (var oreo in Oreos)
    {
        await Html.RenderPartialAsync("Partial/OreoPartial", oreo);
    }

    <div class="card oreo-card oreo-add-data">
        <a class="a-hover grid-center">+ Create</a>
    </div>
</div>